spring:
  config:
    activate:
      on-profile: lottery

mega:
  maxMainNumberValue: 70
  maxBallNumberValue: 25
  results-pattern: (.*);(.*);(.*)

lottery:
  games:
    mega:
      maxMainNumberValue: 70
      maxBallNumberValue: 25
      results-pattern: (.*);(.*);(.*)
    powerball:
      maxMainNumberValue: 69
      maxBallNumberValue: 26
      results-pattern: (.*);(.*);(.*)
