spring:
  config:
    activate:
      on-profile: mega

mega:
  maxMainNumberValue: 70
  maxBallNumberValue: 25
  results-pattern: (.*);(.*);(.*)

lottery:
  powerball:
    maxMainNumberValue: 69
    maxBallNumberValue: 26
    results-pattern: (.*);(.*);(.*)
  mega:
    maxMainNumberValue: 70
    maxBallNumberValue: 25
    results-pattern: (.*);(.*);(.*)
