spring:
  config:
    activate:
      on-profile: rest

logging:
  level:
    org:
      springframework: WARN

lottery:
  games:
    mega:
      filepath: files/MegaMillions.txt
    powerball:
      filepath: files/PowerBall.txt

server:
  port: 10001

springdoc:
  api-docs:
    path: /v1/api-docs
    version: openapi_3_1
  model-and-view-allowed: false
  writer-with-default-pretty-printer: false