spring:
  config:
    activate:
      on-profile: rest

logging:
  level:
    org:
      springframework: WARN

mega:
  filepath: files/MegaMillions.txt

lottery:
  powerball:
    filepath: files/PowerBall.txt
  mega:
    filepath: files/MegaMillions.txt

server:
  port: 10001
