spring:
  config:
    activate:
      on-profile: rest

logging:
  level:
    org:
      springframework: WARN

mega:
  filepath: files/MegaMillions.txt

powerball:
  filepath: files/PowerBall.txt

server:
  port: 10001
